language: node_js
node_js:
  - "7"

script:
  - npm install
  - npm test
  - npm run jsdoc
  - docker-compose -f docker-compose.yml run --rm selenium bash /data/scripts/docker_tests.sh

after_success:
  - scripts/deploy_docs.sh

env:
  global:
    secure:
      YcTG0tlYz/9U+EErVs/tjlbAGhkk8afhbJgi6BBlUzB4+3tDQzw7RAsoTUVppCqbjQtuAsQIISnQ//fGXd8nxIJL0uwe/0RdEeedAsKlbJgiXusDvWjSLTqygok6/MAWW02mOX75XQsvXrrkznb5i1Tru23gi9xXwOa/zksEpUWMBcYBtR7B5KuqhLn9AP0cxfpFNqZ0nbDw+ON8a5/fB3VR1MIhwhBQyxM+/HOpt61zyAx1gZvzmTN7ZnLG2JL1tG8/6oWFvks4gGBuvsYcieZC438yHURzbGc8jW5VUmG5oHXXeSC5h1T+BbJ+UDmumiFVJfiweTkxre8iPlt0WiCQlCnt9qp6sipeORH7uT7+jcrGuqslRJsmjtiIPUc+qO+caJLcQzCZC1+/3ypuhT9tQOAwJYGtwsAGNL+yjwSCZURwIEtpUcB9D5mucrfLIN7P0giSZ9asFzCVHijNfpowWvjk/uwdRlOQBmxdAcOlWn6picsYtH4TU8QSU5WNqAVlE1ta5akdzHcXmFf836R0xeR83IriCgWoE/G8DtXSQU2nChm4bmkPIDPY/1Ob7YVvOM8DvDKvSC/JAujIOIXe0ci3KqmcTb+UFPdRpd7i2YNQVgfAWx6dKWDwCLSfUwtmxlcaQalNr6IF52FdhmnijgDpdxmGnfQ7V7WzZDQ=
